### ISSUE TITLE
Transport error when running with default config

### ISSUE THREAD

**Issue by aphelionz** [Jon-Biz/orbitdb-pinner#4]
```
Pinning previously added orbitdbs:
Orbit-pinner listening on port 3000
(node:29112) UnhandledPromiseRejectionWarning: Error: no valid addresses were provided for transports [TCP,WebSockets,Circuit]
    at TransportManager.listen (/home/mark/Projects/Jon-Biz/orbitdb-pinner/node_modules/ipfs/node_modules/libp2p/src/transport-manager.js:175:21)
    at Libp2p._onStarting (/home/mark/Projects/Jon-Biz/orbitdb-pinner/node_modules/ipfs/node_modules/libp2p/src/index.js:372:33)
    at Libp2p.start (/home/mark/Projects/Jon-Biz/orbitdb-pinner/node_modules/ipfs/node_modules/libp2p/src/index.js:201:18)
    at Proxy.start (/home/mark/Projects/Jon-Biz/orbitdb-pinner/node_modules/ipfs/src/core/components/start.js:58:18)
(node:29112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:29112) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:29112) UnhandledPromiseRejectionWarning: Error: no valid addresses were provided for transports [TCP,WebSockets,Circuit]
    at TransportManager.listen (/home/mark/Projects/Jon-Biz/orbitdb-pinner/node_modules/ipfs/node_modules/libp2p/src/transport-manager.js:175:21)
    at Libp2p._onStarting (/home/mark/Projects/Jon-Biz/orbitdb-pinner/node_modules/ipfs/node_modules/libp2p/src/index.js:372:33)
    at Libp2p.start (/home/mark/Projects/Jon-Biz/orbitdb-pinner/node_modules/ipfs/node_modules/libp2p/src/index.js:201:18)
    at Proxy.start (/home/mark/Projects/Jon-Biz/orbitdb-pinner/node_modules/ipfs/src/core/components/start.js:58:18)
(node:29112) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by aphelionz** [comment]
Downgrading to `ipfs@^0.39.0` fixed it
